using System;
using System.Collections.Generic;

namespace Pos.Api.Models;

// ============================================================
// PLATFORM LAYER — the SaaS control plane that sits above the POS itself:
// device activation, entitlement resolution, tenant lifecycle, vertical packs.
//
// Everything here exists so that "upgrade this tenant", "give them two more
// counters", "suspend them for non-payment" and "this one is a pharmacy, not a
// restaurant" are DATA changes, never code changes.
// ============================================================

/// <summary>
/// Tenant lifecycle. Deliberately graduated rather than a single IsActive bool: a till that
/// stops selling is how you lose a customer permanently, so non-payment walks DOWN this ladder
/// (banner, then back-office, then read-only) instead of jumping straight to a hard lock.
/// </summary>
public enum TenantStatus
{
    /// <summary>Inside the trial window. Full features, capped by the trial plan's quotas.</summary>
    Trial = 1,
    /// <summary>Paid and current. Everything works.</summary>
    Active = 2,
    /// <summary>Invoice overdue. Everything still works; the app shows a payment banner.</summary>
    PastDue = 3,
    /// <summary>Back-office CHANGES locked — settings, catalogue edits, new staff. Viewing and
    /// exporting still work, and the POS still sells. A customer who owes money must always be
    /// able to see their own numbers.</summary>
    Restricted = 4,
    /// <summary>POS can no longer create orders. Existing data stays readable and exportable.</summary>
    ReadOnly = 5,
    /// <summary>Full lock. Nothing but login and the billing screen.</summary>
    Suspended = 6,
    /// <summary>Closed account, retained only for the data-retention window.</summary>
    Cancelled = 7
}

/// <summary>
/// How a tenant's organisation is shaped. This is a structural fact about the business, not a
/// paid feature — every plan can run either shape; the plan only decides HOW MANY locations.
/// </summary>
public enum DeploymentMode
{
    /// <summary>One location that both sells and administers itself.</summary>
    Standalone = 1,

    /// <summary>
    /// A head office with branches beneath it. The head office does not sell — it runs the ERP
    /// (catalogue, purchasing, warehousing, accounting, HR, consolidated reporting) and pushes
    /// down to the branches, which are the only places a till exists.
    /// </summary>
    HeadOffice = 2
}

/// <summary>
/// Which application surface a signed-in user or activated device should see.
///
/// This is derived, never stored: it falls out of the tenant's <see cref="DeploymentMode"/> and
/// which branch the user sits at. Head-office staff at a chain get no POS at all — showing a till
/// to someone who administers a warehouse is clutter at best and a mis-click at worst.
/// </summary>
public enum AppSurface
{
    /// <summary>Sells and administers in one app. A standalone shop.</summary>
    Hybrid = 1,

    /// <summary>Back office only — no till, no checkout, no cash drawer. Head office of a chain.</summary>
    Erp = 2,

    /// <summary>Selling plus the branch-level back office. A branch under a head office.</summary>
    Pos = 3
}

/// <summary>
/// A single-use, short-lived code that activates one device against one branch.
///
/// Replaces the old scheme where a pairing token was DERIVED from public-ish data (branch code
/// plus the first four hex characters of its id), which made it guessable and permanent. A code
/// here is random, hashed at rest (only its prefix is stored in the clear, for display), expires
/// in minutes, can be redeemed once, and must be generated by an authenticated admin who already
/// has access to that branch.
/// </summary>
public class PairingCode
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }
    public Guid BranchId { get; set; }

    /// <summary>SHA-256 of the raw code. The raw value is returned exactly once, at creation.</summary>
    public string CodeHash { get; set; } = string.Empty;

    /// <summary>First 4 characters of the raw code — lets an admin tell two pending codes apart
    /// in the UI without the full value being recoverable from the database.</summary>
    public string CodePrefix { get; set; } = string.Empty;

    /// <summary>Which device class this code may activate. A counter code cannot quietly become a tablet.</summary>
    public TerminalType TerminalType { get; set; } = TerminalType.Counter;

    /// <summary>Pre-assigned name for the terminal this code creates, e.g. "Counter 2".</summary>
    public string TerminalName { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime ExpiresAt { get; set; } = DateTime.UtcNow.AddMinutes(15);
    public Guid CreatedByUserId { get; set; }

    public DateTime? ConsumedAt { get; set; }
    public Guid? ConsumedByTerminalId { get; set; }
    public string? ConsumedByIp { get; set; }
    public bool IsRevoked { get; set; } = false;

    public bool IsRedeemable(DateTime now) => !IsRevoked && ConsumedAt == null && ExpiresAt > now;
}

/// <summary>
/// A manual, per-tenant entitlement change made by the platform owner — the "give this customer
/// three extra counters for a month while their new branch opens" lever.
///
/// Kept separate from <see cref="AddOnSubscription"/> because an add-on is something the tenant
/// BOUGHT (it has a price and belongs on their invoice) whereas an override is something support
/// GRANTED. Mixing the two makes revenue reporting lie.
/// </summary>
public class TenantEntitlementOverride
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }

    /// <summary>Either a SaaSPackageConfig flag name ("HasKitchenDisplay") or a quota key
    /// ("MaxCounters", "MaxBranches", "MaxOrderTabs", "MaxUsers").</summary>
    public string Key { get; set; } = string.Empty;

    /// <summary>"true"/"false" for a flag, or a signed integer DELTA for a quota (e.g. "3", "-1").
    /// A delta rather than an absolute, so a later plan upgrade still raises the floor underneath it.</summary>
    public string Value { get; set; } = string.Empty;

    /// <summary>Null = permanent. Support grants should almost always set this.</summary>
    public DateTime? ExpiresAt { get; set; }
    public string Reason { get; set; } = string.Empty;
    public Guid CreatedByUserId { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public bool IsActive { get; set; } = true;

    public bool IsInForce(DateTime now) => IsActive && (ExpiresAt == null || ExpiresAt > now);
}

/// <summary>
/// Which vertical pack(s) a tenant runs. A pack reshapes the item model, the checkout flow and the
/// screen presets without forking the product — see Data/VerticalPacks.cs for the catalog.
/// A tenant can hold several (a cafe inside a grocery store is Grocery + Restaurant).
/// </summary>
public class TenantVerticalPack
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }
    public string PackKey { get; set; } = string.Empty;

    /// <summary>The pack that decides the default POS layout when several are enabled.</summary>
    public bool IsPrimary { get; set; } = false;
    public DateTime EnabledAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Append-only record of device licence lifecycle events, so "why did this till stop selling?"
/// has an answer that does not depend on someone remembering.
/// </summary>
public class DeviceLicenseEvent
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }
    public Guid? TerminalId { get; set; }
    public Guid? BranchId { get; set; }

    /// <summary>Activated, Renewed, RenewalDenied, Revoked, Deactivated, FingerprintMismatch, QuotaExceeded.</summary>
    public string EventType { get; set; } = string.Empty;
    public string? Detail { get; set; }
    public string? Ip { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// One tenant's fully-resolved entitlement set, cached as a row so every terminal and every
/// request reads the same answer, and so a licence token can carry a version that tells a device
/// its cached copy is stale.
///
/// This is the single source of truth: plan defaults + purchased add-ons + support overrides,
/// collapsed into one place and recomputed whenever any input changes.
/// </summary>
public class TenantEntitlementSnapshot
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }

    /// <summary>Bumped on every recompute. A device licence carries this; a mismatch on heartbeat
    /// tells the device to pull a fresh licence.</summary>
    public int Version { get; set; } = 1;

    public string PlanKey { get; set; } = string.Empty;

    // Resolved quotas (plan + add-ons + overrides already folded in).
    public int MaxBranches { get; set; }
    public int MaxCounters { get; set; }
    public int MaxOrderTabs { get; set; }
    public int MaxUsers { get; set; }

    /// <summary>Resolved boolean feature flags as a JSON object: {"HasKitchenDisplay":true,...}.
    /// JSON rather than columns so adding a feature is a data change, not a migration.</summary>
    public string FeaturesJson { get; set; } = "{}";

    public TenantStatus Status { get; set; } = TenantStatus.Trial;
    public DateTime ComputedAt { get; set; } = DateTime.UtcNow;
}
